
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Bot, MessageCircle, Ticket, Users } from 'lucide-react';

const TelegramBotInterface = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-100 via-purple-50 to-indigo-100">
      <div className="max-w-4xl mx-auto py-8 px-4">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="flex items-center justify-center mb-4">
            <Bot className="w-12 h-12 text-blue-600 mr-3" />
            <h1 className="text-4xl font-bold text-gray-800">Event Tickets Bot</h1>
          </div>
          <p className="text-xl text-gray-600">
            Your automated event ticket management system
          </p>
          <Badge className="mt-2 bg-green-100 text-green-700">
            Bot Status: Active
          </Badge>
        </div>

        {/* Bot Commands */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
          <Card className="hover:shadow-lg transition-shadow">
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center text-lg">
                <MessageCircle className="w-5 h-5 mr-2 text-blue-600" />
                Start Command
              </CardTitle>
            </CardHeader>
            <CardContent>
              <code className="bg-gray-100 px-2 py-1 rounded text-sm font-mono">/start</code>
              <p className="text-sm text-gray-600 mt-2">
                Welcome message and bot introduction
              </p>
            </CardContent>
          </Card>

          <Card className="hover:shadow-lg transition-shadow">
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center text-lg">
                <Ticket className="w-5 h-5 mr-2 text-purple-600" />
                View Events
              </CardTitle>
            </CardHeader>
            <CardContent>
              <code className="bg-gray-100 px-2 py-1 rounded text-sm font-mono">/events</code>
              <p className="text-sm text-gray-600 mt-2">
                Browse all available events and ticket prices
              </p>
            </CardContent>
          </Card>

          <Card className="hover:shadow-lg transition-shadow">
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center text-lg">
                <Users className="w-5 h-5 mr-2 text-green-600" />
                My Tickets
              </CardTitle>
            </CardHeader>
            <CardContent>
              <code className="bg-gray-100 px-2 py-1 rounded text-sm font-mono">/mytickets</code>
              <p className="text-sm text-gray-600 mt-2">
                View all your purchased tickets
              </p>
            </CardContent>
          </Card>

          <Card className="hover:shadow-lg transition-shadow">
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center text-lg">
                <Bot className="w-5 h-5 mr-2 text-orange-600" />
                Purchase Ticket
              </CardTitle>
            </CardHeader>
            <CardContent>
              <code className="bg-gray-100 px-2 py-1 rounded text-sm font-mono">/buy_[event_id]</code>
              <p className="text-sm text-gray-600 mt-2">
                Buy tickets for specific events (generated by /events)
              </p>
            </CardContent>
          </Card>

          <Card className="hover:shadow-lg transition-shadow">
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center text-lg">
                <MessageCircle className="w-5 h-5 mr-2 text-red-600" />
                Help Command
              </CardTitle>
            </CardHeader>
            <CardContent>
              <code className="bg-gray-100 px-2 py-1 rounded text-sm font-mono">/help</code>
              <p className="text-sm text-gray-600 mt-2">
                Show all available commands and usage guide
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Setup Instructions */}
        <Card className="mb-6 border-2 border-blue-200">
          <CardHeader>
            <CardTitle className="text-xl text-blue-800">🔧 Bot Setup Instructions</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h4 className="font-semibold text-gray-800 mb-2">1. Create Telegram Bot</h4>
              <p className="text-sm text-gray-600">
                Message <strong>@BotFather</strong> on Telegram and create a new bot using <code>/newbot</code>
              </p>
            </div>
            <div>
              <h4 className="font-semibold text-gray-800 mb-2">2. Get Bot Token</h4>
              <p className="text-sm text-gray-600">
                Copy the bot token provided by BotFather and add it to your Supabase secrets as <code>TELEGRAM_BOT_TOKEN</code>
              </p>
            </div>
            <div>
              <h4 className="font-semibold text-gray-800 mb-2">3. Set Webhook</h4>
              <p className="text-sm text-gray-600">
                Set your bot webhook URL to: <br />
                <code className="bg-gray-100 px-2 py-1 rounded">
                  https://jxfvuhvnqgvilyskehmg.supabase.co/functions/v1/telegram-webhook
                </code>
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Features */}
        <Card>
          <CardHeader>
            <CardTitle className="text-xl text-gray-800">✨ Bot Features</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-4">
              <div>
                <h4 className="font-semibold text-gray-800 mb-2">Event Management</h4>
                <ul className="text-sm text-gray-600 space-y-1">
                  <li>• Browse available events</li>
                  <li>• View event details and pricing</li>
                  <li>• Real-time ticket availability</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold text-gray-800 mb-2">Ticket System</h4>
                <ul className="text-sm text-gray-600 space-y-1">
                  <li>• Instant ticket purchase</li>
                  <li>• Unique ticket codes</li>
                  <li>• Ticket history and status</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold text-gray-800 mb-2">User Management</h4>
                <ul className="text-sm text-gray-600 space-y-1">
                  <li>• Automatic user registration</li>
                  <li>• Personal ticket management</li>
                  <li>• Purchase history tracking</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold text-gray-800 mb-2">Commands</h4>
                <ul className="text-sm text-gray-600 space-y-1">
                  <li>• Intuitive command interface</li>
                  <li>• Help and guidance</li>
                  <li>• Error handling and feedback</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default TelegramBotInterface;
